apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls
spec:
  secretName: keycloak-tls
  issuerRef:
    name: intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: keycloak.{{ .Values.core.domain }}
  dnsNames:
    - keycloak.{{ .Values.core.domain }}
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: istio-system