apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak-virtualservice
spec:
  hosts:
    - keycloak.{{ .Values.core.domain }}
  gateways:
    - keycloak-gateway
#   tls:
#     - match:
#         - port: 443
#           sniHosts:
#             - "###ZARF_VAR_DOMAIN###"
#       route:
#         - destination:
#             host: httpd-service
#             port:
#               number: 443
  # Comment this `http` section out to disable HTTP
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: {{ .Chart.Name }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80