core:
  domain: ###ZARF_VAR_DOMAIN###

# SUBCHART: bitnami/postgresql/values.yaml
postgresql:
  auth:
    postgresPassword: admin
    username: bn_keycloak
    password: postgres
    database: bitnami_keycloak

# SUBCHART: bitnami/keycloak/values.yaml
keycloak:
  production: true
  auth:
    adminUser: admin
    adminPassword: admin
  postgresql:
    enabled: false # Disable the built-in PostgreSQL deployment
  externalDatabase:
    host: core-postgresql
    port: 5432
    database: bitnami_keycloak
    username: bn_keycloak
    password: postgres
  service:
    http:
      enabled: false
  tls:
    enabled: true
    existingSecret: keycloak-tls
    usePem: true