apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpd-tls-certificate
spec:
  secretName: httpd-tls-secret
  issuerRef:
    name: zarf-ca
  commonName: ###ZARF_VAR_DOMAIN###
  dnsNames:
    - ###ZARF_VAR_DOMAIN###
  privateKey:
    algorithm: RSA
    encoding: PKCS1
