apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpd-tls
  namespace: istio-system
spec:
  secretName: httpd-tls
  issuerRef:
    name: intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: "###ZARF_VAR_DOMAIN###"
  dnsNames:
    - "###ZARF_VAR_DOMAIN###"
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048