apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpd-tls
  namespace: httpd
spec:
  secretName: httpd-tls
  issuerRef:
    name: intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: ###ZARF_VAR_DOMAIN###
  dnsNames:
    - ###ZARF_VAR_DOMAIN###
  privateKey:
    algorithm: ECDSA
    size: 256