apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    app: httpd
  ports:
  - port: 443
    targetPort: 443
    name: https
  # Comment out below to disable HTTP
  - port: 80
    targetPort: 80
    name: http
  